towers_rus_info:
  basic:
    info:
    - 'Дешёвая башня, способная

      давать дополнительные 2

      монеты за убийство.'
    - 'Бонус за убийство

      суммируется с тайлом.'
    links:
    - - tile
      - additional_money
  sniper:
    info:
    - Сильная башня, без эффектов.
  anty_shield:
    info:
    - Игнорирует броню противника.
    - 'На бронибойном тайле не

      приобретает дополнительных

      эффектов.'
    links:
    - - tile
      - piercing_armor
    - - enemy
      - armored
  venom:
    info:
    - 'При ударе по врагу

      накладывает эффект яда.'
    - 'Яд игнорирует броню.

      Тайл яда увеличит урон

      от яда на 1.'
    links:
    - - effect
      - poison
    - - tile
      - poison
  anty_invisible:
    info:
    - 'Раскрывает невидимость

      врагов в своем радиусе.'
    - 'На противоинвизном тайле

      не приобретает

      дополнительных эффектов.'
    links:
    - - enemy
      - invisible
  cutter:
    info:
    - 'Наносит урон всем врагам,

      которых пронизал его луч.'
    - Игнорирует невидимость.
    links:
    - - enemy
      - invisible
  laser:
    info:
    - 'Накладывает эффект лазер.

      Одновременно может наложить

      лазер только на одного врага.'
    links:
    - - effect
      - laser
  cannon:
    info:
    - 'Бьёт в любую точку карты

      и наносит урон всем врагам

      в радиусе взрыва.'
    - 'Игнорирует невидимость.

      Тайл радиуса увеличит

      радиус взрыва.'
enemies_rus_info:
  basic:
    info:
    - Обычный враг без эффектов.
  big:
    info:
    - Враг с увеличенным количеством здоровья.
  regen:
    info:
    - Каждый ход увеличивает свое здоровье.
    links:
    - - tower
      - venom
  armored:
    info:
    - Урон по врагу уменьшается на количество брони вплоть до 0.
    links:
    - - tower
      - anty_shield
  invisible:
    info:
    - Радиус башен по этому врагу уменьшается в 3 раза. Не действует на сплэш-башни
    links:
    - - tower
      - anty_invisible
  giant:
    info:
    - Враг с огромным количеством здоровья.
effects_rus_info:
  poison:
    info:
    - В конце каждого хода наносит урон, ад длительность уменьшается на 1. При нескольких
      эффектах яда наносится наибольший урон, но длительность уменьшается у всех эффектов.
    links:
    - - tower
      - venom
    - - tile
      - poison
  laser:
    info:
    - В конце каждого хода наносит урон. Каждый ход урон увеличивается на 1. Урон
      суммируется от всех лазеров.
    links:
    - - tower
      - laser
tiles_rus_info:
  increase_damage:
    info:
    - Увеличивает урон на 1
  increase_radius:
    info:
    - Увеличивает радиус в 1.5 раза
  piercing_armor:
    info:
    - Башня пробивает броню
    links:
    - - tower
      - anty_shield
    - - enemy
      - armored
  poison:
    info:
    - Дает башне эффект яда
    links:
    - - tower
      - venom
    - - effect
      - poison
  additional_money:
    info:
    - При убийстве 1 дополнительное золото
    links:
    - - tower
      - basic
