towers_rus_info:
  basic:
  - 'Дешёвая башня, способная

    давать дополнительные 2

    монеты за убийство.'
  - 'Бонус за убийство

    суммируется с тайлом.'
  sniper:
  - Сильная башня, без эффектов.
  - Нет.
  anty_shield:
  - Игнорирует броню противника.
  - 'На бронибойном тайле не

    приобретает дополнительных

    эффектов.'
  venom:
  - 'При ударе по врагу

    накладывает эффект яда.'
  - 'Яд игнорирует броню.

    Тайл яда увеличит урон

    от яда на 1.'
  anty_invisible:
  - 'Раскрывает невидимость

    врагов в своем радиусе.'
  - 'На противоинвизном тайле

    не приобретает

    дополнительных эффектов.'
  cutter:
  - 'Наносит урон всем врагам,

    которых пронизал его луч.'
  - Игнорирует невидимость.
  laser:
  - 'Накладывает эффект лазер.

    Одновременно может наложить

    лазер только на одного врага.'
  - Нет.
  cannon:
  - 'Бьёт в любую точку карты

    и наносит урон всем врагам

    в радиусе взрыва.'
  - 'Игнорирует невидимость.

    Тайл радиуса увеличит

    радиус взрыва.'
