0:
  count_waves: 20
  towers:
  - basic
  - sniper
  started_money: 4
  waves:
  - enemies:
    - basic
    - basic
    health_k: 0.0
  - enemies:
    - basic
    - basic
    - basic
    - basic
    health_k: 1.0
  - enemies:
    - basic
    - basic
    - basic
    - basic
    health_k: 1.1
  - enemies:
    - basic
    - big
    - basic
    health_k: 1.3
  - enemies:
    - big
    - big
    - big
    health_k: 2.3
  - enemies:
    - big
    - big
    health_k: 1.8
  - enemies:
    - basic
    - basic
    health_k: 0.9
  - enemies:
    - basic
    - big
    - basic
    health_k: 1.7
  - enemies:
    - big
    - big
    health_k: 2.2
  - enemies:
    - basic
    - basic
    - basic
    - basic
    health_k: 2.0
  - enemies:
    - basic
    - basic
    - basic
    - big
    health_k: 3.0
  - enemies:
    - basic
    - basic
    - big
    - basic
    health_k: 3.1
  - enemies:
    - basic
    - basic
    - basic
    health_k: 1.9
  - enemies:
    - basic
    - basic
    - basic
    health_k: 2.3
  - enemies:
    - basic
    - big
    - basic
    health_k: 3.1
  - enemies:
    - big
    - big
    health_k: 2.9
  - enemies:
    - basic
    - basic
    - big
    - basic
    health_k: 3.6
  - enemies:
    - big
    - big
    - big
    health_k: 4.2
  - enemies:
    - big
    - basic
    health_k: 3.1
  - enemies:
    - basic
    - big
    health_k: 3.0
  map:
  - - 0
    - 3
    - 4
    - 4
    - 4
  - - 4
    - 1
    - 1
    - 1
    - 0
  - - 5
    - 0
    - 6
    - 1
    - 6
  - - 0
    - 1
    - 1
    - 1
    - 4
  - - 4
    - 2
    - 4
    - 0
    - 4
1:
  count_waves: 25
  towers:
  - basic
  - sniper
  - anty_shield
  started_money: 4
  waves:
  - enemies:
    - basic
    - basic
    health_k: 0.0
  - enemies:
    - basic
    - basic
    - basic
    - basic
    health_k: 1.0
  - enemies:
    - basic
    - basic
    - basic
    - basic
    health_k: 1.1
  - enemies:
    - basic
    - armored
    - basic
    health_k: 1.3
  - enemies:
    - basic
    - armored
    - basic
    - armored
    health_k: 2.3
  - enemies:
    - armored
    - basic
    - basic
    health_k: 1.8
  - enemies:
    - basic
    - basic
    health_k: 0.9
  - enemies:
    - big
    - big
    health_k: 1.7
  - enemies:
    - basic
    - basic
    - basic
    - basic
    health_k: 2.2
  - enemies:
    - basic
    - basic
    - armored
    health_k: 2.0
  - enemies:
    - basic
    - big
    - basic
    - basic
    health_k: 3.0
  - enemies:
    - armored
    - basic
    - basic
    - basic
    health_k: 3.1
  - enemies:
    - basic
    - big
    health_k: 1.9
  - enemies:
    - basic
    - big
    health_k: 2.3
  - enemies:
    - basic
    - basic
    - basic
    - basic
    health_k: 3.1
  - enemies:
    - basic
    - big
    - basic
    health_k: 2.9
  - enemies:
    - basic
    - basic
    - big
    - basic
    health_k: 3.6
  - enemies:
    - big
    - big
    - big
    health_k: 4.2
  - enemies:
    - armored
    - basic
    health_k: 3.1
  - enemies:
    - basic
    - basic
    - basic
    health_k: 3.0
  - enemies:
    - basic
    - armored
    - basic
    health_k: 4.0
  - enemies:
    - basic
    - basic
    - armored
    health_k: 3.9
  - enemies:
    - basic
    - basic
    - big
    health_k: 4.2
  - enemies:
    - basic
    - basic
    - armored
    - armored
    health_k: 5.2
  - enemies:
    - basic
    - basic
    - basic
    - basic
    health_k: 4.4
  map:
  - - 3
    - 1
    - 1
    - 1
    - 4
  - - 4
    - 5
    - 4
    - 1
    - 4
  - - 1
    - 1
    - 1
    - 1
    - 0
  - - 1
    - 4
    - 0
    - 7
    - 0
  - - 2
    - 4
    - 6
    - 0
    - 0
2:
  count_waves: 30
  towers:
  - basic
  - sniper
  - anty_shield
  - venom
  started_money: 5
  waves:
  - enemies:
    - basic
    - basic
    health_k: 0.0
  - enemies:
    - regen
    - basic
    health_k: 1.0
  - enemies:
    - basic
    - basic
    - basic
    - basic
    health_k: 1.1
  - enemies:
    - basic
    - regen
    health_k: 1.3
  - enemies:
    - basic
    - regen
    - basic
    - basic
    health_k: 2.3
  - enemies:
    - regen
    - basic
    health_k: 1.8
  - enemies:
    - basic
    - basic
    health_k: 0.9
  - enemies:
    - basic
    - big
    - basic
    health_k: 1.7
  - enemies:
    - basic
    - basic
    - big
    health_k: 2.2
  - enemies:
    - big
    - armored
    health_k: 2.0
  - enemies:
    - big
    - regen
    health_k: 3.0
  - enemies:
    - basic
    - basic
    - big
    - basic
    health_k: 3.1
  - enemies:
    - basic
    - basic
    - basic
    health_k: 1.9
  - enemies:
    - armored
    - basic
    health_k: 2.3
  - enemies:
    - basic
    - regen
    health_k: 3.1
  - enemies:
    - regen
    - basic
    health_k: 2.9
  - enemies:
    - big
    - basic
    - basic
    - basic
    health_k: 3.6
  - enemies:
    - basic
    - armored
    - armored
    - basic
    health_k: 4.2
  - enemies:
    - basic
    - big
    health_k: 3.1
  - enemies:
    - basic
    - armored
    health_k: 3.0
  - enemies:
    - big
    - basic
    - basic
    health_k: 4.0
  - enemies:
    - basic
    - armored
    - basic
    health_k: 3.9
  - enemies:
    - regen
    - basic
    health_k: 4.2
  - enemies:
    - regen
    - armored
    - basic
    health_k: 5.2
  - enemies:
    - basic
    - basic
    - armored
    health_k: 4.4
  - enemies:
    - basic
    - basic
    health_k: 3.7
  - enemies:
    - regen
    - basic
    health_k: 4.7
  - enemies:
    - armored
    - big
    health_k: 5.0
  - enemies:
    - regen
    - basic
    health_k: 4.9
  - enemies:
    - basic
    - basic
    - basic
    - regen
    health_k: 6.0
  map:
  - - 0
    - 0
    - 0
    - 0
    - 0
    - 8
    - 0
  - - 0
    - 0
    - 4
    - 7
    - 1
    - 1
    - 3
  - - 0
    - 8
    - 5
    - 0
    - 1
    - 4
    - 0
  - - 2
    - 1
    - 4
    - 1
    - 1
    - 6
    - 0
  - - 4
    - 1
    - 1
    - 1
    - 4
    - 0
    - 0
3:
  count_waves: 35
  towers:
  - basic
  - sniper
  - anty_shield
  - venom
  - anty_invisible
  started_money: 5
  waves:
  - enemies:
    - basic
    - basic
    health_k: 0.0
  - enemies:
    - basic
    - basic
    - basic
    - basic
    health_k: 1.0
  - enemies:
    - basic
    - basic
    - big
    health_k: 1.1
  - enemies:
    - basic
    - armored
    - basic
    health_k: 1.3
  - enemies:
    - armored
    - regen
    - basic
    health_k: 2.3
  - enemies:
    - basic
    - basic
    - basic
    - basic
    health_k: 1.8
  - enemies:
    - basic
    - basic
    health_k: 0.9
  - enemies:
    - basic
    - basic
    - armored
    health_k: 1.7
  - enemies:
    - basic
    - basic
    - basic
    - basic
    health_k: 2.2
  - enemies:
    - basic
    - basic
    - invisible
    health_k: 2.0
  - enemies:
    - regen
    - basic
    - basic
    health_k: 3.0
  - enemies:
    - big
    - big
    - basic
    health_k: 3.1
  - enemies:
    - basic
    - basic
    - basic
    health_k: 1.9
  - enemies:
    - basic
    - basic
    - basic
    health_k: 2.3
  - enemies:
    - basic
    - basic
    - invisible
    health_k: 3.1
  - enemies:
    - basic
    - basic
    - big
    health_k: 2.9
  - enemies:
    - basic
    - basic
    - armored
    - basic
    health_k: 3.6
  - enemies:
    - basic
    - armored
    - big
    - basic
    health_k: 4.2
  - enemies:
    - invisible
    - basic
    health_k: 3.1
  - enemies:
    - armored
    - basic
    health_k: 3.0
  - enemies:
    - basic
    - regen
    health_k: 4.0
  - enemies:
    - invisible
    - big
    health_k: 3.9
  - enemies:
    - basic
    - armored
    - basic
    health_k: 4.2
  - enemies:
    - big
    - basic
    - regen
    health_k: 5.2
  - enemies:
    - basic
    - basic
    - invisible
    health_k: 4.4
  - enemies:
    - basic
    - basic
    health_k: 3.7
  - enemies:
    - armored
    - basic
    - basic
    health_k: 4.7
  - enemies:
    - regen
    - basic
    health_k: 5.0
  - enemies:
    - basic
    - basic
    - big
    health_k: 4.9
  - enemies:
    - basic
    - regen
    - armored
    health_k: 6.0
  - enemies:
    - basic
    - basic
    - basic
    - armored
    health_k: 5.7
  - enemies:
    - basic
    - basic
    health_k: 4.7
  - enemies:
    - invisible
    - basic
    health_k: 5.3
  - enemies:
    - basic
    - regen
    health_k: 6.0
  - enemies:
    - basic
    - basic
    - armored
    health_k: 5.8
  map:
  - - 0
    - 4
    - 2
    - 0
    - 0
    - 0
    - 0
  - - 4
    - 1
    - 1
    - 4
    - 4
    - 6
    - 0
  - - 4
    - 1
    - 4
    - 1
    - 1
    - 0
    - 0
  - - 0
    - 1
    - 0
    - 3
    - 1
    - 0
    - 4
  - - 8
    - 1
    - 7
    - 0
    - 1
    - 4
    - 0
  - - 0
    - 1
    - 1
    - 1
    - 1
    - 4
    - 0
  - - 4
    - 0
    - 0
    - 5
    - 0
    - 0
    - 0
4:
  count_waves: 40
  towers:
  - basic
  - sniper
  - anty_shield
  - venom
  - anty_invisible
  - laser
  started_money: 6
  waves:
  - enemies:
    - basic
    - basic
    health_k: 0.0
  - enemies:
    - giant
    - basic
    health_k: 1.0
  - enemies:
    - giant
    - basic
    health_k: 1.1
  - enemies:
    - basic
    - basic
    - armored
    health_k: 1.3
  - enemies:
    - armored
    - basic
    - basic
    - armored
    health_k: 2.3
  - enemies:
    - basic
    - basic
    - basic
    - basic
    health_k: 1.8
  - enemies:
    - basic
    - basic
    health_k: 0.9
  - enemies:
    - big
    - big
    health_k: 1.7
  - enemies:
    - basic
    - basic
    - basic
    - basic
    health_k: 2.2
  - enemies:
    - basic
    - basic
    - armored
    health_k: 2.0
  - enemies:
    - basic
    - invisible
    - armored
    health_k: 3.0
  - enemies:
    - basic
    - armored
    - armored
    health_k: 3.1
  - enemies:
    - basic
    - basic
    - basic
    health_k: 1.9
  - enemies:
    - armored
    - basic
    health_k: 2.3
  - enemies:
    - basic
    - basic
    - basic
    - basic
    health_k: 3.1
  - enemies:
    - big
    - invisible
    health_k: 2.9
  - enemies:
    - big
    - regen
    health_k: 3.6
  - enemies:
    - armored
    - basic
    - giant
    health_k: 4.2
  - enemies:
    - basic
    - basic
    - basic
    health_k: 3.1
  - enemies:
    - basic
    - armored
    health_k: 3.0
  - enemies:
    - basic
    - invisible
    - basic
    health_k: 4.0
  - enemies:
    - basic
    - basic
    - big
    health_k: 3.9
  - enemies:
    - basic
    - armored
    - basic
    health_k: 4.2
  - enemies:
    - basic
    - big
    - basic
    - armored
    health_k: 5.2
  - enemies:
    - armored
    - basic
    - basic
    health_k: 4.4
  - enemies:
    - basic
    - basic
    health_k: 3.7
  - enemies:
    - big
    - invisible
    health_k: 4.7
  - enemies:
    - invisible
    - basic
    - basic
    health_k: 5.0
  - enemies:
    - armored
    - basic
    - basic
    health_k: 4.9
  - enemies:
    - basic
    - basic
    - giant
    - basic
    health_k: 6.0
  - enemies:
    - armored
    - regen
    health_k: 5.7
  - enemies:
    - basic
    - basic
    health_k: 4.7
  - enemies:
    - basic
    - basic
    - basic
    health_k: 5.3
  - enemies:
    - invisible
    - basic
    - basic
    health_k: 6.0
  - enemies:
    - regen
    - basic
    health_k: 5.8
  - enemies:
    - basic
    - big
    - big
    health_k: 6.6
  - enemies:
    - basic
    - basic
    - giant
    health_k: 7.0
  - enemies:
    - basic
    - basic
    - basic
    health_k: 5.8
  - enemies:
    - basic
    - big
    health_k: 5.9
  - enemies:
    - invisible
    - armored
    health_k: 6.9
  map:
  - - 0
    - 0
    - 0
    - 0
    - 4
    - 0
    - 0
  - - 4
    - 4
    - 0
    - 1
    - 1
    - 1
    - 0
  - - 0
    - 1
    - 1
    - 1
    - 0
    - 1
    - 8
  - - 4
    - 1
    - 4
    - 9
    - 0
    - 1
    - 4
  - - 5
    - 1
    - 0
    - 0
    - 0
    - 1
    - 4
  - - 0
    - 3
    - 0
    - 6
    - 7
    - 1
    - 2
  - - 0
    - 0
    - 0
    - 0
    - 0
    - 4
    - 0
5:
  count_waves: 40
  towers:
  - basic
  - sniper
  - anty_shield
  - venom
  - anty_invisible
  - laser
  - cutter
  - cannon
  started_money: 6
  waves:
  - enemies:
    - basic
    - basic
    health_k: 0.0
  - enemies:
    - big
    - big
    health_k: 1.0
  - enemies:
    - basic
    - basic
    - basic
    - basic
    health_k: 1.1
  - enemies:
    - regen
    - basic
    health_k: 1.3
  - enemies:
    - basic
    - basic
    - big
    - armored
    health_k: 2.3
  - enemies:
    - basic
    - big
    - basic
    health_k: 1.8
  - enemies:
    - basic
    - basic
    health_k: 0.9
  - enemies:
    - basic
    - giant
    health_k: 1.7
  - enemies:
    - basic
    - basic
    - basic
    - basic
    health_k: 2.2
  - enemies:
    - basic
    - big
    - basic
    health_k: 2.0
  - enemies:
    - basic
    - armored
    - invisible
    health_k: 3.0
  - enemies:
    - basic
    - invisible
    - invisible
    health_k: 3.1
  - enemies:
    - basic
    - big
    health_k: 1.9
  - enemies:
    - armored
    - basic
    health_k: 2.3
  - enemies:
    - basic
    - basic
    - basic
    - basic
    health_k: 3.1
  - enemies:
    - invisible
    - basic
    - basic
    health_k: 2.9
  - enemies:
    - big
    - basic
    - big
    health_k: 3.6
  - enemies:
    - armored
    - basic
    - basic
    - armored
    health_k: 4.2
  - enemies:
    - basic
    - basic
    - basic
    health_k: 3.1
  - enemies:
    - basic
    - basic
    - basic
    health_k: 3.0
  - enemies:
    - big
    - basic
    - basic
    health_k: 4.0
  - enemies:
    - giant
    - basic
    health_k: 3.9
  - enemies:
    - basic
    - basic
    - basic
    - basic
    health_k: 4.2
  - enemies:
    - basic
    - giant
    - basic
    - basic
    health_k: 5.2
  - enemies:
    - basic
    - basic
    - big
    health_k: 4.4
  - enemies:
    - basic
    - basic
    health_k: 3.7
  - enemies:
    - giant
    - basic
    health_k: 4.7
  - enemies:
    - basic
    - basic
    - basic
    - basic
    health_k: 5.0
  - enemies:
    - basic
    - basic
    - basic
    - basic
    health_k: 4.9
  - enemies:
    - basic
    - big
    - giant
    health_k: 6.0
  - enemies:
    - basic
    - invisible
    - armored
    health_k: 5.7
  - enemies:
    - basic
    - basic
    health_k: 4.7
  - enemies:
    - basic
    - armored
    health_k: 5.3
  - enemies:
    - basic
    - basic
    - basic
    - basic
    health_k: 6.0
  - enemies:
    - big
    - armored
    health_k: 5.8
  - enemies:
    - basic
    - big
    - armored
    health_k: 6.6
  - enemies:
    - basic
    - basic
    - armored
    - basic
    health_k: 7.0
  - enemies:
    - big
    - basic
    health_k: 5.8
  - enemies:
    - basic
    - armored
    health_k: 5.9
  - enemies:
    - basic
    - regen
    health_k: 6.9
  map:
  - - 0
    - 0
    - 4
    - 0
    - 0
    - 4
    - 4
  - - 4
    - 1
    - 1
    - 1
    - 1
    - 1
    - 4
  - - 0
    - 3
    - 4
    - 0
    - 0
    - 1
    - 0
  - - 0
    - 0
    - 6
    - 0
    - 7
    - 1
    - 4
  - - 0
    - 4
    - 0
    - 8
    - 0
    - 1
    - 5
  - - 4
    - 0
    - 1
    - 1
    - 1
    - 1
    - 4
  - - 0
    - 4
    - 2
    - 0
    - 9
    - 0
    - 0
