keys:
  1: road
  2: road
  3: base
  4: basic
  5: increase_damage
  6: increase_radius
  7: armor_piercing
  8: poison
  9: additional_money

images_path:
  road: images2d/tile/for_enemies.png
  base: images2d/tile/common_building.png
  basic: images2d/tile/common_building.png
  increase_damage: images2d/tile/damage_up.png
  increase_radius: images2d/tile/radius_up.png
  armor_piercing: images2d/tile/piercing_armor.png
  poison: images2d/tile/poison_up.png
  additional_money: images2d/tile/money_up.png
