towers_characteristics:
  basic:
    basic_damage: 2
    cost: 3
    radius:
      value: 1
    improve_cost_array:
    - 4
    - 6
    additional_money: 2
    targets_state: one_target
    improves:
      basic_damage: 2
      radius: 1.2
    foundation_image: images2d/tower/common_foundation.png
    gun_image: images2d/tower/common_gun.png
  sniper:
    basic_damage: 4
    cost: 5
    radius:
      value: 2
    improve_cost_array:
    - 6
    - 8
    targets_state: one_target
    improves:
      basic_damage: 2
      radius: 1.2
    foundation_image: images2d/tower/sniper_foundation.png
    gun_image: images2d/tower/sniper_gun.png
  anty_shield:
    basic_damage: 3
    cost: 4
    radius:
      value: 1.5
    improve_cost_array:
    - 5
    - 7
    armor_piercing: true
    targets_state: one_target
    improves:
      basic_damage: 2
      radius: 1.2
    foundation_image: images2d/tower/anty_shield.png
  venom:
    basic_damage: 2
    cost: 5
    radius:
      value: 1
    improve_cost_array:
    - 4
    - 6
    poison:
      damage: 2
      duration: 2
    targets_state: one_target
    improves:
      basic_damage: 2
      radius: 1.2
    foundation_image: images2d/tower/venom_foundation.png
    gun_image: images2d/tower/venom_gun.png
  anty_invisible:
    basic_damage: 3
    cost: 4
    radius:
      value: 1.5
    improve_cost_array:
    - 6
    - 8
    vision: true
    targets_state: one_target
    improves:
      basic_damage: 2
      radius: 1.2
    foundation_image: images2d/tower/anty_invisibility_tower.png
  cutter:
    basic_damage: 2
    cost: 5
    radius:
      type_radius: infinity
    improve_cost_array:
    - 8
    - 10
    targets_state: ray
    improves:
      basic_damage: 1
    foundation_image: images2d/tower/cutter_foundation.png
    gun_image: images2d/tower/cutter_gun.png
  laser:
    basic_damage: 0
    cost: 6
    radius:
      value: 1.5
    improve_cost_array:
    - 8
    - 10
    laser:
      damage: 0
    targets_state: one_target
    improves:
      radius: 1.2
    foundation_image: images2d/tower/laser_foundation.png
    gun_image: images2d/tower/laser_gun.png
  cannon:
    basic_damage: 3
    cost: 8
    radius:
      type_radius: infinity_splash
      value: 0.5
    improve_cost_array:
    - 10
    - 12
    targets_state: cannon
    improves:
      basic_damage: 1
    foundation_image: images2d/tower/cannon.png
textures_path:
  charge:
  - images2d/UI/enemy_characteristic/charged.png
  - images2d/UI/enemy_characteristic/not_charged.png
  level:
  - images2d/upgrade/1lvl.png
  - images2d/upgrade/2lvl.png
  - images2d/upgrade/3lvl.png
